### PR TITLE
Allow for a retry on all delete jobs

### PR DESCRIPTION
**Pull request by JohnGarbutt**
On delete, there is no easy way for the user to retry,
the admin has to go and delete job, after seeing a failed job alert.
There is little cost in re-trying delete, in case it is some
transient network error that might be fixed on a second try.

### CODE REVIEW

**Comment by JohnGarbutt** [comment]
it looks like this is borken finding the error:
`    error: Failed to delete platform. Please contact Azimuth operators.
    phase: Failed
    updatedTimestamp: "2023-08-11T15:56:35Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

**Comment by JohnGarbutt** [comment]
Ok, great, that fixed the problem with not finding the error.

**Comment by mkjpryor** [comment]
@JohnGarbutt

My personal opinion is that this should retry forever, with a backoff. As you said before, there is no way for a user to "re-trigger" the delete as Kubernetes already considers the resource as "marked for deletion", and IMHO requiring admin intervention in this case is rubbish.

**Comment by mkjpryor** [comment]
However what you have implemented here is easy and works for now, so LGTM

**Review by mkjpryor — APPROVED** [review]
LGTM

**Pull request merged**
